version: '3.8'

services:
  jenkins:
    build: .  # Constrói a imagem baseada no Dockerfile
    container_name: jenkins-dood
    restart: unless-stopped
    user: root # Garante permissão de escrita no socket
    ports:
      - "8080:8080"   # Porta da interface web
      - "50000:50000" # Porta para agentes JNLP
    volumes:
      - jenkins_home:/var/jenkins_home # Persistência de dados do Jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net: